name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/scripts') }}
          restore-keys: |
            maven-

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Build CitizensBooks with Maven
        run: mvn --batch-mode package -s deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}